[package]
name = "leo-viz"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.31", default-features = false, features = [
    "default_fonts",
    "glow",
    "persistence",
] }
egui = "0.31"
egui_plot = "0.31"
egui_dock = "0.16"
nalgebra = "0.33"
image = "0.25"
log = "0.4"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
eframe = { version = "0.31", default-features = false, features = [
    "default_fonts",
    "glow",
    "persistence",
] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
eframe = { version = "0.31", default-features = false, features = [
    "default_fonts",
    "glow",
    "persistence",
    "web_screen_reader",
] }
wasm-bindgen-futures = "0.4"
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["Window", "Response", "Request", "RequestInit", "RequestMode"] }

[profile.release]
opt-level = 2

[profile.release-wasm]
inherits = "release"
opt-level = "s"
lto = true
