[package]
name = "leo-viz"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.29", default-features = false, features = [
    "default_fonts",
    "glow",
    "persistence",
] }
egui = "0.29"
egui_plot = "0.29"
nalgebra = "0.33"
image = "0.25"
log = "0.4"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
eframe = { version = "0.29", default-features = false, features = [
    "default_fonts",
    "glow",
    "persistence",
] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
eframe = { version = "0.29", default-features = false, features = [
    "default_fonts",
    "glow",
    "persistence",
    "web_screen_reader",
] }
wasm-bindgen-futures = "0.4"
web-sys = "0.3"

[profile.release]
opt-level = 2

[profile.release-wasm]
inherits = "release"
opt-level = "s"
lto = true
